name: 2023 Major League Rugby
round_name: Round
stadia_file: stadia.csv
teams_file: teams.csv
score_settings_file: scoring.csv
schedule_file: schedule.csv
score_table_path: ScoreTables
ranking_directory: ranking
ranking_filename: RankingsRound{}
output_directory: forecasts
report_filename: ReportRound{}
plot_filename: PlotsRound{}
use_spatial_weights: False